# The actual file used for config should be named "bot_config.toml" and should be
# placed in the same directory as bot.py. (Eg. this file is in the correct location.)

# General information required for the bot to function are filled under this header.

[general]
guild_ids=[] # list of server IDs that the bot is a part of


# Configuration style to be followed is one top-level table per cog being configured.

[snipe]      # This lets us know that the following configuration is for the snipe cog
timer=10

[starboard]  # Similarly this is for the starboard cog.
channel=1139734225390669875         # The channel ID where the bot should post the starboard
                                    # messages.
emoji="<:OnP:1139749947357544500>"  # The string representation of the emoji to be used
                                    # as the starboard emoji.
threshold=1                         # The threshold over which the message is posted to the
                                    # starboard channel.

[faq]
gsheet_url = "https://docs.google.com/spreadsheets/d/15vOVv21KZETGxBEBY46H-l5C0WFjLaBUg1xUzFvSk6I/edit#gid=0" # replace this url with your gsheet url
admin_role_name = "mod" # add the name of the role that provides users with elevated permissions to add/delete/modify FAQs

[votedelete]

ignored_channels = [] # Channel IDs where the bot shouldn't be able to delete messages.
emoji = "<:ban:939740396286791741>" # The string representation of the emoji to be used to votedelete messages.
threshold = 5 # The threshold over which the message reacted to will be deleted.