name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: ./
        remote_path: /home/www/my_project/
        remote_host: "ec2-3-131-94-181.us-east-2.compute.amazonaws.com"
        remote_user: "ubuntu"
        remote_key: ${{ secrets.PILOT_EC2_KEY }}
