name: Deploy code to EC2 instance

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH
        run: sudo apt-get install -y ssh

      - name: Copy code to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: "ec2-3-131-94-181.us-east-2.compute.amazonaws.com"
          username: 'ubuntu'
          key: ${{ secrets.PILOT_EC2_KEY }}
          source: '.'
          target: '/home/ubuntu/sherp2'



