name: Deploy code to Droplet

on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          source: '.'
          target: '~/sherp2'

      # - name: 
      #     script : |
      #       cd ~/sherp2
      #       export NVM_DIR=~/.nvm
      #       source ~/.nvm/nvm.sh
      #       npm install pm2
      #       pm2 stop sherp2
      #       pip install -r requirements.txt
      #       pm2 start sherp2


