name: remote ssh command to deploy
on:
  push:
    branches: [ master ]

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
  test:
    runs-on: ubuntu-latest
    name: Typical Usage of OpenVPN
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "./"
        with:
          config_file: ./github/workflows/client.ovpn
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}
          client_key: ${{ secrets.VPN_USER_KEY }}

      - name: kill vpn
        if: always()
        run: sudo killall openvpn
