name: Deploy code to EC2 instance

on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH
        run: sudo apt-get install -y ssh

      - name: Setup SSH
        run: |
          echo "${{ secrets.DROPLET_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 128.199.7.219 >> ~/.ssh/known_hosts
        env:
          DROPLET_KEY: ${{ secrets.DROPLET_KEY }}

      - name: Deploy code
        run: |
          ssh root@128.199.7.219
          cd ~/sherp2
          git pull origin master

        



