name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - run: | 
         sudo -i
         cd ..
         ls
         mkdir -p home/sooraj/sherp3
         chmod +x home/sooraj/sherp3
      - uses: actions/checkout@v3
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PILOT_EC2_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-3-131-94-181.us-east-2.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/sooraj/sherp2"
