name: Weekly JSON Pull of course data

on:
  schedule:
    - cron: "0 0 * * 1"  # Run every Monday at midnight

permissions: read-all|write-all

jobs:
  pull_json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Pull JSON file
        run: |
          curl -o data/ualberta.ca.json -LJ https://raw.githubusercontent.com/steventango/synapse/main/data/ualberta.ca.json
          
      - name: Commit and push changes
        run: |
          git config --global user.email "55115712+Sooraj-beep@users.noreply.github.com"
          git config --global user.name "Sooraj-beep
          git pull
          git add data/ualberta.ca.json
          git commit -m "Update course data"
          git push
